### PR TITLE
Tauri app

### PR DESCRIPTION
**Pull request by karelnagel**
A Tauri app that makes it easier to use LLaMa models. 
Can be run with `pnpm tauri dev`(very slow text generation) or with `pnpm tauri build`.

Features
 - model selecting from your computer or download alpaca 7B from the app
 - starts a new thread with the model running when first message sent (or pressed start button) 
 - remembers the context while the model is running (no context saving yet)
 - ends the thread when pressed stop
 - user can change prompt and parameters
 - saves conversations and settings to local storage

I also added a github action to build the app and release it ,so people can just install it and start using LLaMa models. It needs Apple developer account to sign the app for using on mac, so I used mine for now. The latest release is here: https://github.com/karelnagel/llama-rs/releases/latest.

Feel free to suggest changes, specially in the Rust section, and the ui/ux could also be better.

image

### CODE REVIEW

**Comment by philpax** [comment]
This is awesome, but I'd suggest splitting it out into a separate application. We're considering creating a new organisation, so it'd be perfect to go in there :)

**Comment by karelnagel** [comment]
> This is awesome, but I'd suggest splitting it out into a separate application. We're considering creating a new organisation, so it'd be perfect to go in there :)

Okay yeah that makes sense, closing the PR 🙂

**Comment by hlhr202** [comment]
> This is awesome, but I'd suggest splitting it out into a separate application. We're considering creating a new organisation, so it'd be perfect to go in there :)

@philpax great, i d like to move my work there once you raise it 👍

**Comment by philpax** [comment]
@karelnagel we've got the org now, so feel free to create a repo and we'll bring it into the fold :)

**Pull request closed without merging**
